currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 400
    minimal: 350
    perCubicMeter: 3000

coordinate-range:
  latitudeMin: 45
  latitudeMax: 65
  longitudeMin: 30
  longitudeMax: 96

server:
  port: 8080